import { Project } from '../types/project';

export const projectData: Project[] = [
  {
    id: "event-management-platform",
    title: "Event Management & Planning Platform (Ongoing)",
    description: "Currently developing a comprehensive event management and planning platform using native Android with Jetpack Compose. The goal is to provide a seamless experience for event organizers and attendees, covering aspects like event creation, ticketing, scheduling, and communication.",
    personalNotes: "This is an active, ongoing project focusing on modern Android development practices.",
    technologies: ["Android Native (Kotlin)", "Jetpack Compose", "MVVM Architecture", "Room Database", "Retrofit/Ktor (Networking)", "Firebase", "UI/UX Design (Android)", "Material Design 3"],
    projectUrl: undefined,
    repoUrl: undefined,
  },
  {
    id: "impulse-os",
    title: "Impulse OS - Custom Arch Linux Distro",
    description: "Created and maintain Impulse OS, a custom Arch Linux-based operating system built from archiso. Designed for simplicity and performance, it integrates linux-zen kernels by default and includes essential features for beginners without unnecessary bloat. Contributed Hyprland dotfiles to enhance the user experience, drawing inspiration from Google's Material You design language.",
    personalNotes: "Passionate about creating a streamlined and beautiful Arch Linux experience for both new and experienced users. Ongoing contributions to the Hyprland community.",
    technologies: ["Arch Linux", "Hyprland", "Wayland", "Linux Kernel (linux-zen)", "Shell Scripting (Bash)", "ISO Creation (archiso)", "Dotfiles Management", "UI/UX Design (Material You principles)", "Open Source Contribution", "Git"],
    projectUrl: "https://impulse-os.github.io/",
    repoUrl: "https://github.com/impulse-os", 
  },
  {
    id: "atmos",
    title: "Atmos - Immersive 3D Social Platform",
    description: "Contributed to Atmos, a startup building a Discord-like social video conferencing platform. Elevated the user experience by developing WebGL-driven landing pages and integrating chat APIs within an Unreal Engine 5-based 3D space for truly immersive social interactions.",
    personalNotes: "Gained experience in cutting-edge 3D web technologies and real-time communication within a startup environment.",
    technologies: ["WebGL", "Three.js", "Unreal Engine 5", "Chat API (e.g., Twilio/Pusher)", "3D Modeling Concepts", "Real-time Communication", "Frontend Development", "Startup Environment"],
    projectUrl: undefined,
    repoUrl: undefined,
  },
  {
    id: "legacy",
    title: "Legacy - Alumni Engagement Platform (SIH)",
    description: "Developed \"Legacy\", an alumni association platform using Flutter, as a part of the Smart India Hackathon (SIH). The platform aimed to foster connections, facilitate networking, and manage alumni engagement activities.",
    personalNotes: "Valuable experience in rapid application development with Flutter for a national-level hackathon.",
    technologies: ["Flutter", "Dart", "Mobile App Development", "Cross-Platform Development", "UI/UX (Mobile)", "Firebase (potential backend)"],
    projectUrl: undefined,
    repoUrl: undefined, 
  },
  {
    id: "attendify",
    title: "Attendify - Automated Attendance System",
    description: "Engineered Attendify, an innovative solution for automating attendance tracking. Leveraged Python with OpenCV and dlib libraries to implement facial recognition technology, significantly boosting efficiency and accuracy compared to manual methods.",
    personalNotes: "This project honed my skills in computer vision and machine learning application development.",
    technologies: ["Python", "OpenCV", "dlib", "Facial Recognition", "Machine Learning (Concepts)", "Computer Vision", "Algorithm Development"],
    projectUrl: undefined,
    repoUrl: undefined,
  },
  {
    id: "evoframe",
    title: "Evoframe - Smart Glasses Interaction",
    description: "Developed Evoframe, smart glasses designed to enhance human-computer interaction through intuitive gesture and voice control. Built using a Raspberry Pi and OpenCV for visual input processing.",
    personalNotes: "An exploration into the future of wearable technology and alternative input methods.",
    technologies: ["Raspberry Pi", "Python", "OpenCV", "Gesture Recognition", "Voice Control APIs", "Embedded Systems", "Prototyping", "Human-Computer Interaction (HCI)"],
    projectUrl: undefined,
    repoUrl: undefined,
  },
  {
    id: "drip-limitless",
    title: "Drip Limitless - Social Network & App",
    description: "Led a collaborative team of designers and developers to build Drip Limitless, a feature-rich social networking platform encompassing both a website and an Android application. Key features included real-time chat, user profiles, content sharing, and analytics monitoring to track user engagement.",
    personalNotes: "Spearheaded this project at age 18. Proud to have grown the platform to over 5,000 active members. Simultaneously managed the Norse Music project with the same core team.",
    technologies: ["JavaScript", "PHP", "Node.js", "MySQL", "Docker", "Kodular (Android)", "Real-time Chat (WebSockets)", "Analytics", "Project Management", "Team Leadership", "UI/UX Design"],
    projectUrl: undefined,
    repoUrl: undefined,
  },
  {
    id: "norse-music",
    title: "Norse Music - Streaming Web App",
    description: "Developed Norse Music, a dynamic music streaming web application featuring real-time backend data fetching via the Spotify API. Implemented significant API response time optimizations (30% improvement) and integrated Redis caching for enhanced performance. Added robust search and filtering capabilities, contributing to a notable user engagement increase.",
    personalNotes: "A sister project to Drip Limitless, this deepened my backend and API integration skills. Achieved a 25% increase in user engagement and onboarded over 200 users.",
    technologies: ["Spotify API", "Redis", "Node.js", "Express.js", "API Integration", "Performance Optimization", "Caching Strategies", "Frontend Development (JavaScript)", "Search Algorithms"],
    projectUrl: undefined,
    repoUrl: undefined,
  },
  {
    id: "mahadarshan",
    title: "Mahadarshan - Tourism Website",
    description: "Initiated my web development journey by creating MahaDarshan, a fully responsive and SEO-optimized tourism website. Focused on providing an intuitive user experience for discovering local attractions. Hosted on reliable servers to ensure consistent uptime and performance.",
    personalNotes: "My first major project, built and hosted independently at age 15. This sparked my passion for web development.",
    technologies: ["HTML5", "CSS3", "JavaScript (ES6)", "SEO Best Practices", "Responsive Design", "Web Hosting", "Deployment"],
    projectUrl: undefined, 
    repoUrl: undefined,
  }
]; 